### ISSUE TITLE
프로젝트 구조 및 커스텀 훅 리팩터링 필요

### ISSUE THREAD

**Issue by JongHyeok-Park** [JongHyeok-Park/kmu-toktok-react#61]
## 이슈 내용
- 여러 훅들이 Routes안에 구현되어 있고, 프로젝트 구조가 복잡하여 버그 추적 또는 수정이 어려움
- 특정 routes 또는 components 내에서만 사용되는 커스텀 훅의 경우 해당 component로 모듈화 시킬 필요 있음

## 진행
- 각 routes 또는 components 별로 branch를 생성하여 작업 진행 (ex. refactor/chatbot)
- 작업 후 dev branch로 Pull Request
- 반드시 작업 전 작업할 파트를 반드시 공고 후에 진행

**Comment by thanhhien234** [comment]
리팩토링 끝났습니다
